# Table creation and customization
# Gemilang_POS
# 20 December 2017

# Table Creation

CREATE TABLE CUSTOMER(
    CUSTOMER_ID INT AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(30) NOT NULL,
    CUSTOMER_PHONE VARCHAR(12),
    CONSTRAINT pk_customer PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE PRODUCT(
    PRODUCT_ID INT AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(50) NOT NULL,
    PRODUCT_PURCHASE_PRICE INT NOT NULL,
    PRODUCT_SALE_PRICE INT NOT NULL,
    PRODUCT_STOCK_QUANTITY INT,
    PRODUCT_STOCK_UNIT VARCHAR(8) NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE DISCOUNT_CARD(
    DISCOUNT_ID INT AUTO_INCREMENT,
    DISCOUNT_PHONE VARCHAR(12) NOT NULL,
    CONSTRAINT pk_discount_card PRIMARY KEY (DISCOUNT_ID)
);

CREATE TABLE TRANSACT(
    TRANSACT_ID INT AUTO_INCREMENT,
    TRANSACT_DATE TIMESTAMP NOT NULL,
    CUSTOMER_ID INT DEFAULT 10000001,
    DISCOUNT_ID INT,
    CONSTRAINT pk_transact PRIMARY KEY (TRANSACT_ID),
    CONSTRAINT fk_transact_customer FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID),
    CONSTRAINT fk_transact_discount FOREIGN KEY (DISCOUNT_ID) REFERENCES DISCOUNT_CARD (DISCOUNT_ID)
);

CREATE TABLE TRANSACTLINE(
    TRANSACT_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    TRANSACT_ITEM_QUANTITY INT NOT NULL,
    CONSTRAINT fk_transactline_TRANSACT FOREIGN KEY (TRANSACT_ID) REFERENCES TRANSACT (TRANSACT_ID),
    CONSTRAINT fk_transactline_product FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID),
    CONSTRAINT pk_transactline PRIMARY KEY (TRANSACT_ID,PRODUCT_ID)
);

CREATE TABLE ACCOUNT(
    USER_ID VARCHAR(15),
    USER_PASSWORD VARCHAR(256) NOT NULL,
    USER_ROLE CHAR(1) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (USER_ID)
);

# Auto increment alteration

ALTER TABLE CUSTOMER AUTO_INCREMENT = 10000001;
ALTER TABLE PRODUCT AUTO_INCREMENT = 30000001;
ALTER TABLE DISCOUNT_CARD AUTO_INCREMENT = 40000001;